In [ ]:
"""Question 1

Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function"""
import numpy as np
        
ar1 = np.array([1, 2, 3, 4, 5])
        
ar1 =ar1.tolist()

print(ar1)

[1, 2, 3, 4, 5]


In [ ]:
''' Question 2 
Write a NumPy program to compute the sum of the diagonal elements of a given array.
Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function'''
import numpy as np

ar1 = np.array([[2, 1, 9],
                [3, 5, 1]])

np.trace(ar1)

7

In [ ]:
'''Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
'''
import numpy as np

ar1 = np.array([[2, 1, 9],
                [3, 5, 1]])
li2 = []
x = 4
for f in range(0,2):
  for i in range(0,3):
    m = ar1[f,i]
    if m > x:
      li2.append(m)

print(li2)

[9, 5]


In [ ]:
"""Question 4

Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. """

import numpy as np

a=np.array([[1,2],
           [3,4]])

b=np.array([[5,6],
           [7,8]])

c = a+b
print(c)

[[ 6  8]
 [10 12]]


In [1]:
""""Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function"""

import numpy as np
print("Original matrix:\n")
X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.98805886 0.20495834 0.98765141]
 [0.23890421 0.8708243  0.63415242]
 [0.9106075  0.51812644 0.25604973]]

Subtract the mean of each row of the said matrix:

[[ 0.26116932 -0.5219312   0.26076188]
 [-0.34238943  0.28953065  0.05285878]
 [ 0.34901294 -0.04346811 -0.30554482]]
